import os
import torch

RECOGNITION_DEVICE = os.getenv("RECOGNITION_DEVICE", "cuda" if torch.cuda.is_available() else "cpu")
DETECTION_CONFIDENCE_THRESHOLD = float(os.getenv("DETECTION_CONFIDENCE_THRESHOLD", "0.85"))
RECOGNITION_SIMILARITY_THRESHOLD = float(os.getenv("RECOGNITION_SIMILARITY_THRESHOLD", "0.75"))
TEMPORAL_VERIFICATION_FRAMES = int(os.getenv("TEMPORAL_VERIFICATION_FRAMES", "4"))
MODEL_VERSION = "facenet_v1"
EMBEDDING_DIMENSION = 512
MAX_FACES_PER_FRAME = int(os.getenv("MAX_FACES_PER_FRAME", "10"))

print(f"ML Pipeline Bootrapping on: {RECOGNITION_DEVICE}, Threshold: {RECOGNITION_SIMILARITY_THRESHOLD}")
